title: Metadata
arrange:
  - author.md
  - citation.md
  - description.md
  - funder.md
  - identifier.md
  - keywords.md
  - license.md
  - name.md
  - schemaVersion.md
  - url.md
  - usageInfo.md
  - variableMeasured.md